name: ヘルスチェック

on:
  workflow_dispatch:
  schedule:
    # 5分ごとに実行
    - cron:  '*/5 * * * *'

jobs:
  toda-tasks-notification:
    name: Hobigonヘルスチェック
    runs-on: ubuntu-latest
    steps:
      - run: |
          STATUS=$(curl -X GET -I '${{ secrets.HEALTH_CHECK_ENDPOINT_HOBIGON }}' -o /dev/null -w '%{http_code}' -s)
          if [ ! $STATUS = '200' ]; then
            curl -X POST \
            -H 'Content-type: application/json' \
            -d "{
                 \"text\": \"【Hobigon】ヘルスチェック失敗（StatusCode: $STATUS）\"
               }" ${{ secrets.SLACK_WEBHOOK_URL_TO_50 }};
          fi
          
          
