name: 生協入金リマインド

on:
  schedule:
    - cron: '0 0,3 1,15 * *'

jobs:
  parking-payment-notification:
    name: 生協入金リマインド
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H 'Content-Type:application/json' \
          -H 'Authorization: Bearer ${{ secrets.LINE_API_TOKEN }}' \
          -d '{
                "to": "${{ secrets.LINE_CHAT_ROOM_TO_MOTHER }}",
                "messages":[
                  {
                    "type": "text",
                    "text": "今日は生協に入金する日"
                  }
                ]
              }' https://api.line.me/v2/bot/message/push
