name: 本日のタスク通知

on:
  schedule:
    - cron: '0 4,10,22 * * *'

jobs:
  toda-tasks-notification:
    name: 本日のタスク通知
    runs-on: ubuntu-latest
    steps:
      - run: curl --location --request POST '${{ secrets.TODAY_TASKS_NOTIFICATION_ENDPOINT }}'
